/**
 * Test 9: Report page shows "Continue track" after completing a track round.
 *
 * When an InterviewSession has metadata.companyTrackId + metadata.roundIndex,
 * the report page shows a "Continue" or "Track complete" card.
 *
 * The pre-fill flow is /interview/new?companyTrackId=google&roundIndex=0&...
 * which should embed the track context in the session.
 */
import { test, expect } from '@playwright/test'

test('interview/new page with companyTrackId param shows track context banner', async ({ page }) => {
  await page.goto('/interview/new?companyTrackId=google&roundIndex=0&format=coding&skill=Algorithms')
  await page.waitForLoadState('networkidle')

  const url = page.url()
  const redirectedToAuth = url.includes('/login') || url.includes('/signin') || url.includes('/onboarding')
  if (redirectedToAuth) {
    test.skip(true, 'Requires candidate auth — set TEST_CANDIDATE_EMAIL/PASSWORD')
    return
  }

  // Should show Google track context banner
  const hasTrackBanner = await page.locator('text=Google track').isVisible().catch(() => false)
  const hasRoundInfo = await page.locator('text=Round 1').isVisible().catch(() => false)
  const hasTrackLabel = await page.locator('text=track').first().isVisible().catch(() => false)

  console.log('[test-09] Track banner:', hasTrackBanner, 'Round 1:', hasRoundInfo, 'Any track:', hasTrackLabel)

  // The interview form should load
  const hasContent = await page.locator('h1, h2, button').first().isVisible().catch(() => false)
  expect(hasContent).toBe(true)

  // Should not show 500
  const has500 = await page.locator('text=500').isVisible().catch(() => false)
  expect(has500).toBe(false)
})

test('interview/new pre-fills format from URL param', async ({ page }) => {
  await page.goto('/interview/new?companyTrackId=meta&roundIndex=0&format=system_design&skill=Distributed+Systems')
  await page.waitForLoadState('networkidle')

  const url = page.url()
  const redirectedToAuth = url.includes('/login') || url.includes('/signin') || url.includes('/onboarding')
  if (redirectedToAuth) {
    test.skip(true, 'Requires candidate auth')
    return
  }

  // System design should be pre-selected or visible
  const hasSysDesign = await page.locator('text=System Design').first().isVisible().catch(() => false)
  console.log('[test-09] System Design format visible:', hasSysDesign)

  const has500 = await page.locator('text=500').isVisible().catch(() => false)
  expect(has500).toBe(false)
})

test('report page /interview/report/[id] loads without error for valid id format', async ({ page }) => {
  // Use a mongo-id-shaped string that won't exist — expect 404 or loading state
  await page.goto('/interview/report/000000000000000000000000')
  await page.waitForLoadState('networkidle')

  const url = page.url()
  if (url.includes('/login') || url.includes('/signin')) {
    // Good — redirected to login instead of crashing
    return
  }

  // Should not 500
  const has500 = await page.locator('text=Internal Server Error').isVisible().catch(() => false)
  expect(has500).toBe(false)
})

test('continue track link format is correct', async ({ page }) => {
  // Verify the URL structure that would be generated by the report page "Continue" CTA
  // This is a URL-construction test — we check the link would have the right params
  const expectedParams = new URLSearchParams({
    companyTrackId: 'google',
    roundIndex: '1',
    format: 'system_design',
    skill: 'System Design',
  })

  const href = `/interview/new?${expectedParams.toString()}`
  expect(href).toContain('companyTrackId=google')
  expect(href).toContain('roundIndex=1')
  expect(href).toContain('format=system_design')

  // Navigate to that URL and verify it doesn't error
  await page.goto(href)
  await page.waitForLoadState('networkidle')

  const has500 = await page.locator('text=500').isVisible().catch(() => false)
  expect(has500).toBe(false)
})
